#!/bin/sh
previous_list_file="/tmp/firmware_upgrading_temp/luci.list.preinst"
if [ -f $previous_list_file ]; then
	local new_file_list="`cat /usr/lib/opkg/info/luci.list`"
	for i in $new_file_list
	do
		local j=${i#*/tmp/firmware_upgrading_temp/luci}
		if [ ! -f $j ]; then
			local j_dir=${j%/*}
			if [ ! -d $j_dir ]; then
				mkdir -p $j_dir
			fi
			cp $i $j
		elif [ `ls -l $j | awk '{print $5}'` != `ls -l $i | awk '{print $5}'` ]; then
			cp $i $j
		elif [ -n "`cmp $j $i `" ]; then
			cp $i $j
		fi
		sed -i "s#^$j\$##;/^$/d" $previous_list_file
	done
	local previous_file_list="`cat $previous_list_file`"
	for i in $previous_file_list
	do
		rm $i >>/dev/null 2>&1
	done
else
	cp /tmp/firmware_upgrading_temp/luci/usr / -rf
	cp /tmp/firmware_upgrading_temp/luci/etc / -rf
	cp /tmp/firmware_upgrading_temp/luci/www / -rf
fi
sed -i "s/\/tmp\/firmware_upgrading_temp\/luci//g" /usr/lib/opkg/info/luci.list

uci set luci.main.mediaurlbase=/luci-static/dinstar.default
uci rename system.@system[0]=main
uci rename dropbear.@dropbear[0]=main
uci rename dhcp.@dnsmasq[0]=dnsmasq
uci rename firewall.@defaults[0]=defaults
uci commit luci
uci commit system
uci commit dropbear
uci commit dhcp
uci commit firewall

if [ -n "`cmp /usr/lib/lua/luci/scripts/restore_default /bin/restore_default`" ]; then
	cp /usr/lib/lua/luci/scripts/restore_default /bin/restore_default
fi

if [ -n "`cmp /usr/lib/lua/luci/scripts/dynamic_dns_functions.sh /usr/lib/ddns/dynamic_dns_functions.sh`" ]; then
	cp /usr/lib/lua/luci/scripts/dynamic_dns_functions.sh /usr/lib/ddns/dynamic_dns_functions.sh
fi

if [ -n "`cmp /usr/lib/lua/luci/scripts/dynamic_dns_updater.sh /usr/lib/ddns/dynamic_dns_updater.sh`" ]; then
	cp /usr/lib/lua/luci/scripts/dynamic_dns_updater.sh /usr/lib/ddns/dynamic_dns_updater.sh
fi

if [ -n "`cmp /usr/lib/lua/luci/scripts/ddns /etc/init.d/ddns`" ]; then
	cp /usr/lib/lua/luci/scripts/ddns /etc/init.d/ddns
fi

if [ ! -f /etc/hotplug.d/iface/50-freeswitch ] || [ -f /etc/hotplug.d/iface/50-freeswitch -a -n "`cmp /usr/lib/lua/luci/scripts/50-freeswitch /etc/hotplug.d/iface/50-freeswitch`" ]; then
	cp /usr/lib/lua/luci/scripts/50-freeswitch /etc/hotplug.d/iface/50-freeswitch
fi

if [ ! -L /usr/bin/patch ]; then
	ln -s /usr/lib/lua/luci/scripts/patch /usr/bin/patch
fi

/etc/init.d/lucid stop
rm /tmp/luci-indexcache >>/dev/null 2>&1
#pid=`pgrep -f "lua -lluci.lucid -e luci.lucid.start()"`
#for x in $pid
#do
#    kill -9 $x >>/dev/null 2>&1
#done

if [ -f /tmp/prov/etc/luci ]; then
	cp /tmp/prov/etc/luci /etc/config
fi

#if [ -f /tmp/lucid_setting ]; then
#	uci_http_address=`head -n 1 /tmp/lucid_setting`
#	uci set lucid.http.address=${uci_http_address}
#	
#	uci_https_address=`tail -n 1 /tmp/lucid_setting`
#	if [ ${uci_https_address} ] && [ ${uci_https_address} != ${uci_http_address} ]; then
#		uci set lucid.https.address=${uci_https_address}
#	fi
#
#	uci commit lucid
#	rm -f /tmp/lucid_setting
#fi

if [ -f /tmp/lucid_setting ]; then
	uci_http_address=`head -n 1 /tmp/lucid_setting`
	if [ ! -z "${uci_http_address}" ]; then
		uci delete lucid.http.address -q
		for address in ${uci_http_address}
		do
			uci add_list lucid.http.address="${address}"
		done
	fi
	
	uci_https_address=`tail -n 1 /tmp/lucid_setting`
	if [ ! -z "${uci_https_address}" ] && [ "${uci_https_address}" != "${uci_http_address}" ]; then
		uci delete lucid.https.address -q
		for address in ${uci_https_address}
		do
			uci add_list lucid.https.address="${address}"
		done
	fi

	uci commit lucid
	rm -f /tmp/lucid_setting
fi

if [ -f /tmp/prov/etc/callcontrol ]; then
	cp /tmp/prov/etc/callcontrol  /etc/config
fi

if [ -f /tmp/prov/etc/profile_sip ]; then
	cp /tmp/prov/etc/profile_sip  /etc/config
fi

if [ -f /tmp/prov/etc/profile_codec ]; then
	cp /tmp/prov/etc/profile_codec /etc/config
fi

if [ -f /tmp/prov/etc/profile_fxso ]; then
	cp /tmp/prov/etc/profile_fxso /etc/config
fi

if [ -f /tmp/prov/etc/endpoint_fxso ]; then
	cp /tmp/prov/etc/endpoint_fxso /etc/config
fi

if [ -f /tmp/prov/etc/endpoint_mobile ]; then
	cp /tmp/prov/etc/endpoint_mobile /etc/config
fi

if [ -f /tmp/prov/etc/fax ]; then
	cp /tmp/prov/etc/fax /etc/config
fi

if [ -f /tmp/prov/etc/feature_code ]; then
	cp /tmp/prov/etc/feature_code /etc/config
fi

if [ -f /tmp/prov/etc/ivr ]; then
	cp /tmp/prov/etc/ivr /etc/config
fi

if [ -f /tmp/prov/etc/provision ]; then
	cp /tmp/prov/etc/provision /etc/config
fi

if [ -f /tmp/prov/etc/gre ]; then
	cp /tmp/prov/etc/gre /etc/config
fi

if [ -f /tmp/prov/etc/pptpc ]; then
	cp /tmp/prov/etc/pptpc /etc/config
fi

if [ -f /tmp/prov/etc/xl2tpd ]; then
	cp /tmp/prov/etc/xl2tpd /etc/config
fi

if [ -f /tmp/prov/etc/openvpn ]; then
	cp /tmp/prov/etc/openvpn /etc/config
fi

rm -rf /tmp/prov/etc
sleep 2
/etc/init.d/lucid enable

/etc/init.d/lucid start
lua /usr/lib/lua/luci/scripts/data_upgrade.lua
