#!/bin/sh

if [ -f "/etc/crontabs/root" ]; then
	sed -i '/update_passwd/d' /etc/crontabs/root
	echo '1 0 * * * /usr/bin/check_cdr.sh &' >> /etc/crontabs/root
else
	echo '1 0 * * * /usr/bin/check_cdr.sh &' > /etc/crontabs/root
fi

cp /tmp/firmware_upgrading_temp/oem/usr/bin/check_cdr.sh /usr/bin/check_cdr.sh
cp /tmp/firmware_upgrading_temp/oem/usr/bin/backup_cdr.sh /usr/bin/backup_cdr.sh
cp /tmp/firmware_upgrading_temp/oem/oem /etc/config/oem
cp /tmp/firmware_upgrading_temp/oem/luci /usr/lib/lua/ -r

echo > /usr/lib/opkg/info/oem.list
cat > /usr/lib/opkg/info/oem.list << EOF
/usr/lib/lua/luci/scripts/default_config/dhcp
/usr/lib/lua/luci/scripts/default_config/feature_code
/usr/lib/lua/luci/scripts/default_config/firewall
/usr/lib/lua/luci/scripts/default_config/network
/usr/lib/lua/luci/scripts/default_config/wireless
/usr/lib/lua/luci/scripts/default_config/endpoint_siptrunk
/usr/lib/lua/luci/scripts/default_config/profile_codec
/usr/lib/lua/luci/scripts/default_config/system
/usr/lib/lua/luci/scripts/default_config/telnet
/usr/lib/lua/luci/model/cbi/admin_system/led.lua
EOF
