#!/bin/sh

if [ "$INTERFACE" = "wan" ] && [ "$ACTION" = "ifup" ] ; then
	stat=`uci get wireless.wifi0.disabled -q`
	mode=`uci get wireless.wifi0.mode -q`
	if [ ! -z $stat ] && [ ! -z $mode ] && [ "$stat" = "0" ] && [ "$mode" = "sta" ]; then
		ubus call network.wireless down
		ubus call network.wireless up
	fi
fi
