#!/bin/sh
local in_factory="`uci -q -c /tmp get factory_test.@device[0].test_status`"
local rst_counts
if [ "$in_factory" = "testing" -o "$in_factory" = "start" ]; then
	if [ -z `uci -q -c /tmp get factory_test.@button[0]` ]; then
		uci -c /tmp/ add factory_test button
		uci -c /tmp/ rename factory_test.@button[0]=button
	fi
	rst_counts="`uci -c /tmp get factory_test.@button[0].rst_counts`"
	if [ -z "$rst_counts" ]; then
		$rst_counts=0
	fi

	rst_counts=$(($rst_counts + 1))
	logger "$BUTTON pressed for $SEEN seconds rst_counts $rst_counts"

	echo "reset button seen $SEEN rst_counts $rst_counts" > /dev/console
	uci -c /tmp set factory_test.@button[0].rst_counts="$rst_counts"
	uci -c /tmp commit factory_test
else

	[ "${ACTION}" = "released" ] || {
		button0_watch.sh &
		exit 0
	}

	[ "${ACTION}" = "released" ] && {
		killall button0_watch.sh
	}

	. /lib/functions.sh

	logger "$BUTTON pressed for $SEEN seconds"

	echo "`date '+%Y-%m-%d %a %H:%M:%S'` RST Button pressed for $SEEN seconds" >>/etc/log/button_log
	#echo "reset button seen $SEEN" > /dev/console

	if [ "$SEEN" -lt 6 ]
	then
		echo "timer" > /sys/class/leds/uc100-run/trigger
		echo "1000" > /sys/class/leds/uc100-run/delay_on
		echo "1000" > /sys/class/leds/uc100-run/delay_off
	elif [ "$SEEN" -ge 6 ] && [ "$SEEN" -le 11 ]
	then
		sleep 1
		sync
		reboot -f
	elif [ "$SEEN" -ge 12 ]
	then
		echo "timer" > /sys/class/leds/uc100-run/trigger
		echo "1000" > /sys/class/leds/uc100-run/delay_on
		echo "1000" > /sys/class/leds/uc100-run/delay_off
	fi
fi
