#!/bin/sh

echo "restore factory" > /dev/console
if [ -f /usr/lib/lua/luci/scripts/reset_default_config.lua ]; then
	lua /usr/lib/lua/luci/scripts/reset_default_config.lua
else
	[ -f /etc/config/wireless ] && {
		local wifimode
		config_load wireless
		config_get wifimode wifi0 mode
		[ -n "$wifimode" ] && [ "$wifimode" = "sta" ] && {
			echo > /etc/config/network
			cat > /etc/config/network << EOF
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fdca:5f92:f802::/48'

config interface 'eth0'
        option ifname 'eth0'
        option macaddr '00:11:22:33:44:55'

config interface 'lan'
        option ifname 'eth0.1'
        option force_link '1'
        option macaddr '00:11:22:33:44:55'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.11.1'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option disabled '0'

config interface 'wlan'
        option ifname 'wlan0'
        option force_link '1'
        option proto 'dhcp'
EOF
		}
		[ -n "$wifimode" ] && [ "$wifimode" = "ap" ] && {
			echo > /etc/config/network
			cat > /etc/config/network << EOF
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fdca:5f92:f802::/48'

config interface 'eth0'
        option ifname 'eth0'
        option macaddr '00:11:22:33:44:55'

config interface 'lan'
        option ifname 'eth0.1'
        option force_link '1'
        option macaddr '00:11:22:33:44:55'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.11.1'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option disabled '0'

config interface 'wan'
        option ifname 'eth0.2'
        option force_link '1'
        option macaddr '00:11:22:33:44:56'
        option proto 'dhcp'

config interface 'wan2'
        option ifname 'ppp0'
        option disabled '1'
        option userdisabled '0'
        option proto '3g'
        option device '/dev/ttyUSB3'
        option apn 'cmnet'
        option dialnumber '*99#'
        option service 'umts'
        option metric '20'

config interface 'wan6'
        option ifname 'eth0.2'
        option proto 'dhcpv6'

config interface 'wlan'
        option ifname 'wlan0'
        option force_link '1'
        option proto 'dhcp'
EOF
		}
	}
	/etc/init.d/network restart

	(echo "admin";sleep 1;echo "admin")|passwd admin > /dev/null
fi

echo "none" > /sys/class/leds/uc100-run/trigger
echo "0" > /sys/class/leds/uc100-run/brightness
sleep 5
sync
reboot -f
