#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

if [ "$IFNAME" == "ppp1701" ]; then
	lock /tmp/service_state_log_lock
	echo "Date:`date '+%Y-%m-%d %H:%M:%S'`, Service:L2TP, State:Logout" >> /ramlog/service_state_log
	lock -u /tmp/service_state_log_lock
fi

if [ "$IFNAME" == "ppp1723" ]; then
	lock /tmp/service_state_log_lock
	echo "Date:`date '+%Y-%m-%d %H:%M:%S'`, Service:PPTP, State:Logout" >> /ramlog/service_state_log
	lock -u /tmp/service_state_log_lock
fi
