#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 1 1
proto_set_keep 1
[ -n "$PPP_IPPARAM" ] && {
	[ -n "$IPLOCAL" ] && proto_add_ipv4_address "$IPLOCAL" 32 "" "${IPREMOTE:-2.2.2.2}"
	[ -n "$IPREMOTE" ] && proto_add_ipv4_route 0.0.0.0 0 "$IPREMOTE"
	[ -n "$LLLOCAL" ] && proto_add_ipv6_address "$LLLOCAL" 128
	[ -n "$DNS1" ] && proto_add_dns_server "$DNS1"
	[ -n "$DNS2" -a "$DNS1" != "$DNS2" ] && proto_add_dns_server "$DNS2"
}
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}

if [ "$IFNAME" == "ppp1701" ]; then
	#echo "ip route add default via $5 dev $1" >> /tmp/ppp1701.log
	l2tpdr=`uci get xl2tpd.main.defaultroute`
	if [ "$l2tpdr" == "1" ]; then
		ip route add default via $5 dev $1 metric 5
	fi
	
	vc_server=`uci get xl2tpd.main.server`                               
	vc_user=`uci get xl2tpd.main.username`                        
	vc_domain=`cat /var/run/vpn_domains | grep "^l2tpc " | awk '{print $3}' | head -1`
	if [ "$vc_domain" == "" ]; then                                         
		echo "login: user:$vc_user, server:$vc_server, local ip:$4, gateway:$5, login date:`date '+%Y-%m-%d %H:%M:%S'`" >> /ramlog/l2tpc_log
	else                                                                                                       
		echo "login: user:$vc_user, server:$vc_server/$vc_domain, local ip:$4, gateway:$5, login date:`date '+%Y-%m-%d %H:%M:%S'`" >> /ramlog/l2tpc_log
	fi

	ppp_ipaddr="$4"
	vpn_ip1=${ppp_ipaddr%%.*}                       
	vpn_ip2=${ppp_ipaddr%.*.*}                      
	vpn_ip3=${ppp_ipaddr%.*}
	if [ $vpn_ip1 -le 126 ]; then
        #echo "$vpn_ip1.0.0.0/8"
		iptables -w -t mangle -D mwan3_connected -d $vpn_ip1.0.0.0/8 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		iptables -w -t mangle -A mwan3_connected -d $vpn_ip1.0.0.0/8 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		ip route add $vpn_ip1.0.0.0/8 dev $1 src $4  metric 1711
	elif [ $vpn_ip1 -le 191 ]; then
        #echo "$vpn_ip2.0.0/16"
		iptables -w -t mangle -D mwan3_connected -d $vpn_ip2.0.0/16 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		iptables -w -t mangle -A mwan3_connected -d $vpn_ip2.0.0/16 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		ip route add $vpn_ip2.0.0/16 dev $1 src $4  metric 1711
	elif [ $vpn_ip1 -le 223 ]; then
        #echo "$vpn_ip3.0/24"
		iptables -w -t mangle -D mwan3_connected -d $vpn_ip3.0/24 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		iptables -w -t mangle -A mwan3_connected -d $vpn_ip3.0/24 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		ip route add $vpn_ip3.0/24 dev $1 src $4  metric 1711
	fi	

	lock /tmp/service_state_log_lock
	echo "Date:`date '+%Y-%m-%d %H:%M:%S'`, Service:L2TP, State:Login" >> /ramlog/service_state_log
	lock -u /tmp/service_state_log_lock
fi

if [ "$IFNAME" == "ppp1723" ]; then
	dr=`uci get pptpc.main.defaultroute`
	if [ "$dr" == "1" ]; then
		ip route add default via $5 dev $1 metric 6
	fi
	
	vc_server=`uci get pptpc.main.server`
	vc_user=`uci get pptpc.main.username`
	vc_domain=`cat /var/run/vpn_domains | grep "^pptpc " | awk '{print $3}' | head -1`
	if [ "$vc_domain" == "" ]; then
		echo "login: user:$vc_user, server:$vc_server, local ip:$4, gateway:$5, login date:`date '+%Y-%m-%d %H:%M:%S'`" >> /ramlog/pptpc_log
	else
		echo "login: user:$vc_user, server:$vc_server/$vc_domain, local ip:$4, gateway:$5, login date:`date '+%Y-%m-%d %H:%M:%S'`" >> /ramlog/pptpc_log
	fi

	ppp_ipaddr="$4"
	vpn_ip1=${ppp_ipaddr%%.*}
	vpn_ip2=${ppp_ipaddr%.*.*}
	vpn_ip3=${ppp_ipaddr%.*}
	if [ $vpn_ip1 -le 126 ]; then
		#echo "$vpn_ip1.0.0.0/8"
		iptables -w -t mangle -D mwan3_connected -d $vpn_ip1.0.0.0/8 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null                 
		iptables -w -t mangle -A mwan3_connected -d $vpn_ip1.0.0.0/8 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		ip route add $vpn_ip1.0.0.0/8 dev $1 src $4 metric 1733
	elif [ $vpn_ip1 -le 191 ]; then
		#echo "$vpn_ip2.0.0/16"
		iptables -w -t mangle -D mwan3_connected -d $vpn_ip1.0.0/16 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null                 
		iptables -w -t mangle -A mwan3_connected -d $vpn_ip1.0.0/16 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		ip route add $vpn_ip2.0.0/16 dev $1 src $4 metric 1733
	elif [ $vpn_ip1 -le 223 ]; then
		#echo "$vpn_ip3.0/24"
		iptables -w -t mangle -D mwan3_connected -d $vpn_ip3.0/24 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null                 
		iptables -w -t mangle -A mwan3_connected -d $vpn_ip3.0/24 -j MARK --set-xmark 0xff00/0xff00 2>/dev/null
		ip route add $vpn_ip3.0/24 dev $1 src $4 metric 1733
	fi

	lock /tmp/service_state_log_lock
	echo "Date:`date '+%Y-%m-%d %H:%M:%S'`, Service:PPTP, State:Login" >> /ramlog/service_state_log
	lock -u /tmp/service_state_log_lock
fi

if [ -n "$AUTOIPV6" ]; then
	json_init
	json_add_string name "${PPP_IPPARAM}_dhcpv6"
	json_add_string ifname "@$PPP_IPPARAM"
	json_add_string proto "dhcpv6"
	json_close_object
	ubus call network add_dynamic "$(json_dump)"
fi
