#!/bin/sh

cp /rom/bin/button0_watch.sh /bin/button0_watch.sh
cp /rom/bin/button1_watch.sh /bin/button1_watch.sh
cp /rom/bin/network_watch /bin/network_watch

[ -f "/usr/lib/lua/luci/scripts/default_config/BTN_0" ] && {
	cp /usr/lib/lua/luci/scripts/default_config/BTN_0 /etc/rc.button/BTN_0
	rm /usr/lib/lua/luci/scripts/default_config/BTN_0
} || {
	cp /rom/etc/rc.button/BTN_0 /etc/rc.button/BTN_0
}

[ -f "/usr/lib/lua/luci/scripts/default_config/BTN_1" ] && {
	cp /usr/lib/lua/luci/scripts/default_config/BTN_1 /etc/rc.button/BTN_1
	rm /usr/lib/lua/luci/scripts/default_config/BTN_1
} || {
	cp /rom/etc/rc.button/BTN_1 /etc/rc.button/BTN_1
}

[ -f "/etc/crontabs/root" ] && sed -i '/update_passwd/d' /etc/crontabs/root
/etc/init.d/cron restart
[ -f "/usr/bin/update_passwd.sh" ] && rm /usr/bin/update_passwd.sh

homeultera_exist=`cat /etc/passwd | grep '^homeultera:'`
[ ! -z "$homeultera_exist" ] && deluser "homeultera"

sed -i "s/option sessiontime .*/option sessiontime '3600'/g" /etc/config/luci

[ -f "/usr/bin/dhcp_hook.sh" ] && rm /usr/bin/dhcp_hook.sh
[ -f "/etc/config/dhcp" ] && sed -i "/dhcpscript/d" /etc/config/dhcp

[ -f "/etc/init.d/dropbear" ] && /etc/init.d/dropbear enable
