#!/bin/sh

if [ ! -f "/etc/init.d/extension" ] || [ ! -f "/lib/modules/3.10.14/raeth_ubg.ko" ] || [ -n "`cmp /etc/init.d/extension /tmp/firmware_upgrading_temp/filesystem/extension`" ] || [ -n "`cmp /lib/modules/3.10.14/raeth_ubg.ko /tmp/firmware_upgrading_temp/filesystem/raeth_ubg.ko`" ]; then
	cp /tmp/firmware_upgrading_temp/filesystem/raeth_ubg.ko /lib/modules/3.10.14/raeth_ubg.ko
	cp /tmp/firmware_upgrading_temp/filesystem/extension /etc/init.d/extension
	chmod +x /etc/init.d/extension

	uci delete network.port8 -q
	wan_at=`cat /proc/wan_at`
	[ "$wan_at" = "4" ] && {
		uci set network.wan.wan_switch="on"
	} || {
		uci set network.wan.wan_switch="off"
	}
	uci commit network
fi

echo "/etc/init.d/extension" > /usr/lib/opkg/info/filesystem.list
