#!/bin/sh

#rm /usr/lib/lua/luci/model/cbi/admin_detailset -rf
#rm /usr/lib/lua/luci/model/cbi/admin_wizard -rf
#rm /usr/lib/lua/luci/view/admin_advanced -rf
#rm /usr/lib/lua/luci/view/admin_affair -rf
#rm /usr/lib/lua/luci/view/admin_detailset -rf
#rm /usr/lib/lua/luci/view/admin_wizard -rf

rm /etc/log/service_state_log -rf
rm /ramlog/service_state_log -rf
rm /etc/config/vpnselect -rf

wifi_mode=`uci get wireless.wifi0.mode`
if [ ! -z "$wifi_mode" ] && [ "$wifi_mode" = "sta" ]; then
	rm /etc/config/wireless -rf

	macaddr=$(readwifimac)
	if [ -z "$macaddr" ]; then
		macaddr=$(cat /sys/class/net/ra0/address)
	fi
	myssid=${macaddr//:/}
	myssid=${myssid:6}
	echo > /etc/config/wireless
	cat > /etc/config/wireless <<EOF
config wifi-device  ra0
	option type     mt7620a
	option channel  11
	option hwmode   11bgn
	option htmode HT20/HT40
	option isolate 0
	option txpower 50
	option wdsmode disable
	option wps     off
	# REMOVE THIS LINE TO ENABLE WIFI:
	option disabled 0

config wifi-iface wifi0
	option device   ra0
	option ifname	ra0
	option index	1
	option network  lan
	option mode     ap
	option wmm      0
	option isolate  0
	option ssid     domain_$myssid
	option encryption none
EOF
	rm /etc/config/network_tmp -rf
	cp /usr/lib/lua/luci/scripts/default_config/network /etc/config/network
	mv /usr/lib/lua/luci/scripts/change_wireless_dat.sh /tmp/
	sh /tmp/change_wireless_dat.sh
else
	rm /usr/lib/lua/luci/scripts/change_wireless_dat.sh -rf
	uci delete network_tmp.network.access_mode -q
	uci commit network_tmp -q
fi

cp /rom/bin/network_watch /bin/network_watch
cp /rom/bin/restore_default /bin/restore_default
cp /rom/bin/restore_factory /bin/restore_factory
cp /rom/etc/openvpn/client_down.sh /etc/openvpn/client_down.sh
cp /rom/etc/openvpn/client_up.sh /etc/openvpn/client_up.sh
cp /rom/lib/netifd/ppp-down /lib/netifd/ppp-down

kernelver=`cat /proc/kernelversion`
kernelver=${kernelver%%.*}
wifiver=`cat /proc/wifiversion`
wifiver=${wifiver%%.*}
if [ "$kernelver" = "6" ] && [ "$wifiver" = "4" ]; then
	cp /rom/lib/netifd/wireless/mt7620a.sh /lib/netifd/wireless/mt7620a.sh
fi

uci set lucid.http.address='80' -q
uci delete firewall.defaults.enabled_8345 -q
uci delete firewall.defaults.enabled_8848 -q
uci delete firewall.redirecta -q
uci delete firewall.rulea -q
uci delete firewall.redirectb -q
uci delete firewall.ruleb -q
uci commit lucid -q
uci commit firewall -q

