#!/bin/sh

cp /tmp/firmware_upgrading_temp/oem/etc/config/* /usr/lib/lua/luci/scripts/default_config/
cp /tmp/firmware_upgrading_temp/oem/oem /etc/config/oem
cp /tmp/firmware_upgrading_temp/oem/luci /usr/lib/lua/ -rf
cp /tmp/firmware_upgrading_temp/oem/icons /www/luci-static/resources/ -rf

uci set lucid.http.address=80
uci add_list lucid.http.address=8345
uci add_list lucid.http.address=8848
uci commit lucid

if [ -f "/usr/lib/lua/luci/controller/mini/index.lua" ]; then
	cp /tmp/firmware_upgrading_temp/oem/etc/config/* /etc/config/
	uci set system.main.zonename=Asia/Beijing
	uci set system.main.timezone=CST-8
	uci commit system
else
	uci set firewall.defaults.enabled_8345=1
	uci set firewall.defaults.enabled_8848=0

	uci delete firewall.redirecta -q
	section=`uci add firewall redirect`
	section_name="redirecta"
	uci set firewall.${section}.name='Allow-8345'
	uci set firewall.${section}.src='wan'
	uci set firewall.${section}.src_dport='8345'
	uci set firewall.${section}.dest_port='8345'
	uci set firewall.${section}.enabled='1'
	uci rename firewall.${section}=${section_name}

	uci delete firewall.rulea -q
	section=`uci add firewall rule`
	section_name="rulea"
	uci set firewall.${section}.name='Allow-8345'
	uci set firewall.${section}.src='wan'
	uci set firewall.${section}.dest_port='8345'
	uci set firewall.${section}.target='ACCEPT'
	uci set firewall.${section}.enabled='1'
	uci rename firewall.${section}=${section_name}

	uci delete firewall.redirectb -q
	section=`uci add firewall redirect`
	section_name="redirectb"
	uci set firewall.${section}.name='Allow-8848'
	uci set firewall.${section}.src='wan'
	uci set firewall.${section}.src_dport='8848'
	uci set firewall.${section}.dest_port='8848'
	uci set firewall.${section}.enabled='1'
	uci rename firewall.${section}=${section_name}

	uci delete firewall.ruleb -q
	section=`uci add firewall rule`
	section_name="ruleb"
	uci set firewall.${section}.name='Allow-8848'
	uci set firewall.${section}.src='wan'
	uci set firewall.${section}.dest_port='8848'
	uci set firewall.${section}.target='ACCEPT'
	uci set firewall.${section}.enabled='1'
	uci rename firewall.${section}=${section_name}

	uci commit firewall
fi

echo "/www/luci-static/resources/icons/correct.png" > /usr/lib/opkg/info/oem.list
echo "/www/luci-static/resources/icons/error.png" >> /usr/lib/opkg/info/oem.list
echo "/www/luci-static/resources/icons/info.png" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/controller/admin/advanced.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/controller/admin/affair.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/controller/admin/detailset.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/controller/admin/wizard.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_wizard/ddns.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_wizard/l2tp_client.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_wizard/net_access.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_wizard/pptp_client.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_wizard/sim.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_wizard/siptrunk.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_wizard/wlan_ap.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_detailset/ddns.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_detailset/l2tp_client.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_detailset/net_access.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_detailset/pptp_client.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_detailset/sim.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_detailset/siptrunk.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/model/cbi/admin_detailset/wlan_ap.lua" >> /usr/lib/opkg/info/oem.list
echo "/usr/lib/lua/luci/scripts/change_wireless_dat.sh" >> /usr/lib/opkg/info/oem.list
echo "/etc/hotplug.d/iface/54-ra0" >> /usr/lib/opkg/info/oem.list
echo "/etc/freeswitch/scripts/service_state_log.lua" >> /usr/lib/opkg/info/oem.list

/etc/init.d/firewall restart >/dev/null 2>&1
/etc/init.d/lucid restart >/dev/null 2>&1
